name: Main Branch CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  GATEWAY_IMAGE_NAME: ${{ github.repository }}/gateway-api
  EMAIL_IMAGE_NAME: ${{ github.repository }}/email-service
  AUTH_IMAGE_NAME: ${{ github.repository }}/auth-service

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test Gateway API
        run: |
          dotnet restore GatewayAPI/GatewayAPI.csproj
          dotnet build GatewayAPI/GatewayAPI.csproj --configuration Release
          # Add tests if you have them
          # dotnet test GatewayAPI.Tests/GatewayAPI.Tests.csproj

      - name: Build and test Email Service
        run: |
          dotnet restore EmailService/EmailService.csproj
          dotnet build EmailService/EmailService.csproj --configuration Release
          # Add tests if you have them
          # dotnet test EmailService.Tests/EmailService.Tests.csproj

      - name: Build and test Auth Service
        run: |
          dotnet restore AuthenticationService/AuthenticationService.csproj
          dotnet build AuthenticationService/AuthenticationService.csproj --configuration Release
          # Add tests if you have them
          # dotnet test AuthService.Tests/AuthService.Tests.csproj

      - name: Build and push Docker images
        run: |
          # Build and push Gateway API
          docker build -t ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:latest ./GatewayAPI
          docker push ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:latest

          # Build and push Email Service
          docker build -t ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:latest ./EmailService
          docker push ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:latest

          # Build and push Auth Service
          docker build -t ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:latest ./AuthenticationService
          docker push ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            # Create deployment directory
            mkdir -p /deployments/microservices
            cd /deployments/microservices

            # Check if network exists, if not create it
            NETWORK_EXISTS=$(docker network ls --format "{{.Name}}" | grep -w "microservices-network" || true)
            if [ -z "$NETWORK_EXISTS" ]; then
              echo "Creating microservices-network..."
              docker network create microservices-network
            else
              echo "Network microservices-network already exists"
            fi

            # Login to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull latest images
            docker pull ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:latest
            docker pull ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:latest
            docker pull ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:latest

            # Create docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3.8'

            services:
              sqlserver:
                image: mcr.microsoft.com/mssql/server:2022-latest
                container_name: sqlserver-microservices
                environment:
                  - ACCEPT_EULA=Y
                  - SA_PASSWORD=YourStrong@Passw0rd
                  - MSSQL_PID=Express
                ports:
                  - "1433:1433"
                networks:
                  - microservices-network
                volumes:
                  - sqlserver_data:/var/opt/mssql
                restart: unless-stopped

              kafka:
                image: confluentinc/cp-kafka:latest
                container_name: kafka-microservices
                environment:
                  KAFKA_NODE_ID: 1
                  KAFKA_PROCESS_ROLES: broker,controller
                  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
                  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
                  KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093
                  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
                  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
                  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
                  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
                  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
                  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
                  KAFKA_NUM_PARTITIONS: 3
                ports:
                  - "9092:9092"
                networks:
                  - microservices-network
                restart: unless-stopped

              kafka-init:
                image: confluentinc/cp-kafka:latest
                container_name: kafka-init
                depends_on:
                  - kafka
                networks:
                  - microservices-network
                entrypoint: ["/bin/sh", "-c"]
                command: |
                  "
                  echo 'Waiting for Kafka to be ready...'
                  sleep 30
                  kafka-topics --create --topic user-registered --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --if-not-exists
                  echo 'Topic user-registered created successfully'
                  "

              auth-service:
                image: ${{ env.REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:latest
                container_name: auth-service
                environment:
                  - ASPNETCORE_ENVIRONMENT=Production
                  - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AuthDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
                  - Kafka__BootstrapServers=kafka:9092
                ports:
                  - "5001:80"
                depends_on:
                  - sqlserver
                  - kafka
                networks:
                  - microservices-network
                restart: unless-stopped
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:80/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3

              email-service:
                image: ${{ env.REGISTRY }}/${{ env.EMAIL_IMAGE_NAME }}:latest
                container_name: email-service
                environment:
                  - ASPNETCORE_ENVIRONMENT=Production
                  - Kafka__BootstrapServers=kafka:9092
                ports:
                  - "5002:80"
                depends_on:
                  - kafka
                networks:
                  - microservices-network
                restart: unless-stopped
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:80/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3

              gateway-api:
                image: ${{ env.REGISTRY }}/${{ env.GATEWAY_IMAGE_NAME }}:latest
                container_name: gateway-api
                environment:
                  - ASPNETCORE_ENVIRONMENT=Production
                  - Services__AuthService=http://auth-service:80
                  - Services__EmailService=http://email-service:80
                ports:
                  - "5000:80"
                depends_on:
                  - auth-service
                  - email-service
                networks:
                  - microservices-network
                restart: unless-stopped
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:80/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3

            networks:
              microservices-network:
                driver: bridge

            volumes:
              sqlserver_data:
            EOL

            # Stop existing containers
            docker-compose down --remove-orphans

            # Start all services
            docker-compose up -d

            # Wait for services to start
            echo "Waiting for services to start..."
            sleep 60

            # Check container status
            echo "=== Container Status ==="
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

            # Check health status
            echo "=== Health Check Results ==="
            echo "Gateway API Health:"
            curl -f http://localhost:5000/health || echo "Gateway API health check failed"
            echo ""
            echo "Auth Service Health:"
            curl -f http://localhost:5001/health || echo "Auth Service health check failed"
            echo ""
            echo "Email Service Health:"
            curl -f http://localhost:5002/health || echo "Email Service health check failed"

            # Check logs for any errors
            echo "=== Recent Logs ==="
            docker-compose logs --tail=20 